clmgf:
  onoff: false
  value: 
clmrg:
  onoff: false
  value:
left_border:
  onoff: false
  value:
left_border_width:
  onoff: false
  value: 10
top_border:
  onoff: false
  value:
top_border_width:
  onoff: false
  value: 10
right_border:
  onoff: false
  value:
right_border_width:
  onoff: false
  value: 10
bottom_border:
  onoff: false
  value:
bottom_border_width:
  onoff: false
  value: 10
left_padding:
  onoff: false
  value: 10
top_padding:
  onoff: false
  value: 10
right_padding:
  onoff: false
  value: 10
bottom_border:
  onoff: false
  value: 10
left_align:
  onoff: true
  value: 
center_align:
  onoff: false
  value: 
right_align:
  onoff: false
  value: 
justify_align:
  onoff: false
  value:
bracket_open:
  onoff: true
  value:  
bold:
  onoff: false
  value: 
italic:
  onoff: false
  value: 
fs:
  onoff: true
  value: 20
fontcolor:
  onoff: false
  value: 
font:
  onoff: true
  value: Arial
value:
  onoff: true
  value: 
bracket_close:
  onoff: true
  value:  
cellx:
  onoff: true
  value: