clmgf:
  constructive: false
  value: 
clmrg:
  constructive: false
  value:
left_border:
  constructive: false
  value:
left_border_width:
  constructive: false
  value: 10
top_border:
  constructive: false
  value:
top_border_width:
  constructive: false
  value: 10
right_border:
  constructive: false
  value:
right_border_width:
  constructive: false
  value: 10
bottom_border:
  constructive: false
  value:
bottom_border_width:
  constructive: false
  value: 10
left_padding:
  constructive: false
  value: 10
top_padding:
  constructive: false
  value: 10
right_padding:
  constructive: false
  value: 10
bottom_border:
  constructive: false
  value: 10
left_align:
  constructive: true
  value: 
center_align:
  constructive: false
  value: 
right_align:
  constructive: false
  value: 
justify_align:
  constructive: false
  value:
bracket_open:
  constructive: true
  value:  
bold:
  constructive: false
  value: 
italic:
  constructive: false
  value: 
fs:
  constructive: true
  value: 20
fontcolor:
  constructive: false
  value: 
font:
  constructive: true
  value: Arial
value:
  constructive: true
  value: 
bracket_close:
  constructive: true
  value:  
cellx:
  constructive: true
  value: